name: example
description: This is an example
author: Lucas David Traverso
maintainer: lucas6246@gmail.com

_common/lib: !include ../utils/package.common.yaml

<<: *ghcoptions
<<: *extensions

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- conferer
- conferer-warp
- conferer-aeson
- conferer-dhall

executables:
  example-exe:
    main: Main
    source-dirs: src
