resolver: lts-24.17
compiler: ghc-9.10.3
allow-newer: true
notify-if-nix-on-path: false

packages:
  - ./packages/conferer/
  - ./packages/aeson/
  - ./packages/yaml/
  - ./packages/dhall/
  - ./packages/warp/
  - ./packages/hspec/
  - ./packages/snap/
  - ./packages/hedis/
  - ./example/

extra-deps:
  - dhall-json-1.7.12
