resolver: lts-18.28

packages:
  - ./packages/conferer/
  - ./packages/aeson/
  - ./packages/yaml/
  - ./packages/dhall/
  - ./packages/warp/
  - ./packages/hspec/
  - ./packages/snap/
  - ./packages/hedis/
  - ./example/
