resolver: lts-20.4

packages:
  - ./packages/conferer/
  - ./packages/aeson/
  - ./packages/yaml/
  - ./packages/dhall/
  - ./packages/warp/
  - ./packages/hspec/
  - ./packages/snap/
  - ./packages/hedis/
  - ./example/

extra-deps:
  - snap-core-1.0.5.0
  - snap-server-1.1.2.0
  - readable-0.3.1
