resolver: lts-22.4
# allow-newer: true

packages:
  - ./packages/conferer/
  - ./packages/aeson/
  - ./packages/yaml/
  - ./packages/dhall/
  - ./packages/warp/
  - ./packages/hspec/
  - ./packages/snap/
  - ./packages/hedis/
  - ./example/

extra-deps:
- dhall-json-1.7.12@sha256:11e3b8eff71da871d8e965a8c3a00ee2666b5d103295132824cff47232fdc365,4517
