name: conferer-dhall
version: 1.1.0.0
synopsis: |
  Configuration for reading dhall files
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 1.1.0.0 && < 2.0.0.0
  - conferer-aeson >= 1.1.0.0 && < 2.0.0.0
  - bytestring >= 0.10 && < 0.12
  - text >= 1.1 && < 2.1
  - directory >= 1.2 && < 2.0
  - dhall >= 1.8 && < 2.0
  - dhall-json >= 1.0 && < 2.0

tests:
  specs:
    main: ConfererDhallSpecMain
    source-dirs: test
    dependencies:
    - conferer-dhall
    - hspec
