name: conferer-hspec
version: 1.1.1.0
synopsis: |
  conferer's FromConfig instances for hspec Config
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

flags:
  no-hspec-api:
    description: Disable the hspec-api library dependency for older versions of hspec
    default: false
    manual: false


dependencies:
  - base >= 4.3 && < 5
  - conferer >= 1.1.0.0 && < 2.0.0.0
  - text >= 1.1 && < 2.2
  - hspec-core >= 2.0.0 && < 2.12.0

when:
  - condition: '! flag(no-hspec-api)'
    dependencies: hspec-api

tests:
  specs:
    main: ConfererHspecSpecMain
    source-dirs: test
    dependencies:
    - conferer-hspec
    - hspec
