name: conferer-aeson
version: 1.1.0.2
synopsis: |
  conferer's source for reading json files
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 4.19.0.0
  - conferer >= 1.1.0.0 && < 2.0.0.0
  - bytestring >= 0.10 && < 0.13
  - text >= 1.1 && < 2.2
  - directory >= 1.2 && < 2.0

  # json
  - aeson >= 0.10 && < 2.3
  # These should be constrained by aeson right?
  - vector
  - unordered-containers

tests:
  specs:
    main: ConfererAesonSpecMain
    source-dirs: test
    dependencies:
    - conferer
    - conferer-aeson
    - hspec
    - aeson-qq
