name: conferer-warp
version: 1.1.0.0
synopsis: |
  conferer's FromConfig instances for warp settings
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - conferer >= 1.1.0.0 && < 2.0.0.0
  - text >= 1.1 && < 2.2
  - warp >= 3.0 && < 4.0
  - wai >= 3.0 && < 4.0
  - http-types >= 0.8.6 && < 0.13

tests:
  specs:
    main: ConfererWarpSpecMain
    source-dirs: test
    dependencies:
    - conferer-warp
    - hspec
