name: conferer
version: 1.1.0.0
synopsis: |
  Configuration management library
description: |
  Library to abstract the parsing of many haskell config values from different config sources

_common/lib: !include ../../utils/package.common.yaml

<<: *everything

dependencies:
  - base >= 4.3 && < 5
  - containers >= 0.5 && < 0.8
  - bytestring >= 0.10 && < 0.13
  - text >= 1.1 && < 2.2
  - directory >= 1.2 && < 2.0
  - filepath >= 1.0 && < 2.0

tests:
  specs:
    main: ConfererSpecMain
    source-dirs: test
    dependencies:
      - conferer
      - hspec
      - deepseq
      - QuickCheck

